<?php

namespace App\Actions;

use App\Reports\DepotPerformanceReport;
// use Dompdf\Dompdf;
// use Dompdf\Options;
use Spatie\LaravelPdf\Facades\Pdf;
class ExportDepotPerformancePdf
{
    public function execute(array $filters = []): mixed
    {
        $report = new DepotPerformanceReport;
        $data = $report->generate($filters);
        $summary = $report->getSummary($filters);

        $html = $this->generateHtml($data, $summary, $filters);

        $filename = 'depot_performance_'.now()->format('Y-m-d_H-i-s').'.pdf';

        return response()->streamDownload(function () use ($html, $filename) {
            echo Pdf::html($html)
                ->format('a4')
                ->landscape()
                ->name($filename)
                ->toResponse(request());
        }, $filename);
    }

    private function generateHtml($data, $summary, $filters): string
    {
        $startDate = $filters['start_date'] ?? now()->startOfYear()->format('Y-m-d');
        $endDate = $filters['end_date'] ?? now()->endOfYear()->format('Y-m-d');
        $depotName = $filters['depot_name'] ?? 'All Depots';

        $html = '
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Depot Performance Report</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .header { text-align: center; margin-bottom: 30px; }
                .summary { margin-bottom: 30px; }
                .summary-card { display: inline-block; margin: 10px; padding: 15px; border: 1px solid #ddd; border-radius: 5px; text-align: center; min-width: 150px; }
                .summary-value { font-size: 24px; font-weight: bold; color: #2563eb; }
                .summary-label { font-size: 12px; color: #666; margin-top: 5px; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                th { background-color: #f5f5f5; font-weight: bold; }
                .text-right { text-align: right; }
                .text-center { text-align: center; }
                .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Depot Performance Report</h1>
                <p>Generated on: '.now()->format('F d, Y \a\t g:i A').'</p>
                <p>Period: '.\Carbon\Carbon::parse($startDate)->format('M d, Y').' - '.\Carbon\Carbon::parse($endDate)->format('M d, Y').'</p>
                <p>Depot Filter: '.htmlspecialchars($depotName, ENT_QUOTES, 'UTF-8').'</p>
            </div>

            <div class="summary">
                <div class="summary-card">
                    <div class="summary-value">'.number_format($summary['depot_count']).'</div>
                    <div class="summary-label">Total Depots</div>
                </div>
                <div class="summary-card">
                    <div class="summary-value">'.number_format($summary['total_dispatches']).'</div>
                    <div class="summary-label">Total Dispatches</div>
                </div>
                <div class="summary-card">
                    <div class="summary-value">₦'.number_format($summary['total_revenue'], 2).'</div>
                    <div class="summary-label">Total Revenue</div>
                </div>
                <div class="summary-card">
                    <div class="summary-value">₦'.number_format($summary['average_revenue_per_depot'], 2).'</div>
                    <div class="summary-label">Avg Revenue/Depot</div>
                </div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>Depot Name</th>
                        <th class="text-right">Total Dispatches</th>
                        <th class="text-right">ATC Cost (₦)</th>
                        <th class="text-right">Transport Cost (₦)</th>
                        <th class="text-right">Total Revenue (₦)</th>
                    </tr>
                </thead>
                <tbody>';

        foreach ($data as $depot) {
            $html .= '
                    <tr>
                        <td>'.htmlspecialchars($depot['depot_name'], ENT_QUOTES, 'UTF-8').'</td>
                        <td class="text-right">'.number_format($depot['total_dispatches']).'</td>
                        <td class="text-right">'.number_format($depot['total_atc_cost'], 2).'</td>
                        <td class="text-right">'.number_format($depot['total_transport_cost'], 2).'</td>
                        <td class="text-right">'.number_format($depot['total_revenue'], 2).'</td>
                    </tr>';
        }

        $html .= '
                </tbody>
            </table>

            <div class="footer">
                <p>This report was generated by RBC Trucking Management System</p>
            </div>
        </body>
        </html>';

        return $html;
    }
}
